pot = lambda c:f'  WHILEPOTENCIA: NOP\n\tPUSHL -2\n\tPUSHI 0\n\tSUP\n\tJZ ENDWHILEPOTENCIA\n\tPUSHL -3\n\
\tPUSHL -1\n\t{c}MUL\n\tSTOREL -3\n\tPUSHL -2\n\tPUSHI 1\n\tSUB\n\tSTOREL -2\n\tJUMP WHILEPOTENCIA\n\
  ENDWHILEPOTENCIA: NOP\n\tRETURN\n'
fact = f'  WHILEFACTORIAL: NOP\n\tPUSHL -1\n\tPUSHI 1\n\tSUP\n\tJZ ENDWHILEFACTORIAL\n\tPUSHL -2\n\tPUSHL -1\n\
\tMUL\n\tSTOREL -2\n\tPUSHL -1\n\tPUSHI 1\n\tSUB\n\tSTOREL -1\n\tJUMP WHILEFACTORIAL\nENDWHILEFACTORIAL: NOP\n\tRETURN\n'
exponencial = f'FORSYSEXP: NOP\n\tPUSHL -2\n\tPUSHI 13\n\tINF\n\tJZ ENDFORSYSEXP\n\tPUSHL -3\n\tPUSHF 1.0\n\tPUSHL -2\n\
\tPUSHL -1\n\tPUSHA SYSPOTENCIA\n\tCALL\n\tNOP\n\tPOP 2\n\tPUSHI 1\n\tPUSHL -2\n\tPUSHA SYSFACTORIAL\n\tCALL\n\tNOP\n\
\tPOP 1\n\tITOF\n\tFDIV\n\tFADD\n\tSTOREL -3\n\tPUSHL -2\n\tPUSHI 1\n\tADD\n\tSTOREL -2\n\tJUMP FORSYSEXP\n\nENDFORSYSEXP: NOP\n\tRETURN\n'
logaritmo = f'\tPUSHI 1\n\tSTOREL -2\nFORSYSLN: NOP\n\tPUSHL -2\n\tPUSHI 50\n\tINF\n\tJZ ENDFORSYSLN\n\tPUSHL -3\n\
\tPUSHI 1\n\tITOF\n\tPUSHL -2\n\tITOF\n\tFDIV\n\tPUSHF 1.0\n\tPUSHL -2\n\tPUSHI 1\n\tITOF\n\tPUSHI 1\n\tITOF\n\tPUSHL -1\n\
\tFDIV\n\tFSUB\n\tPUSHA SYSPOTENCIA\n\tCALL\n\tNOP\n\tPOP 2\n\tFMUL\n\tFADD\n\tSTOREL -3\n\tPUSHL -2\n\tPUSHI 1\n\tADD\n\
\tSTOREL -2\n\tJUMP FORSYSLN\nENDFORSYSLN: NOP\n\tRETURN\n'